const movies = [
  {
    title: "Birds of Prey",
    img: "birdsofprey.webp",
    rating: 3.0,
    duration: "1h 49min",
    year: 2020,
    language: "English", country: "USA", popularity: 1500,
    genre: ["Action", "Adventure"],
    director: "Cathy Yan",
    synopsis: "After splitting with the Joker, Harley Quinn joins superheroes Black Canary, Huntress, and Renee Montoya to save a young girl from an evil crime lord."
  },
  {
    title: "La La Land",
    img: "lalaland.jpg",
    rating: 4.0,
    duration: "2h 8min",
    year: 2016,
    language: "English", country: "USA", popularity: 2500,
    genre: ["Romance", "Drama"],
    director: "Damien Chazelle",
    synopsis: "A jazz pianist falls for an aspiring actress in Los Angeles, but as success mounts, their love faces obstacles."
  },
  {
    title: "Inception",
    img: "inception.jpg",
    rating: 4.4,
    duration: "2h 28min",
    year: 2010,
    language: "English", country: "USA", popularity: 3500,
    genre: ["Action", "Sci-Fi"],
    director: "Christopher Nolan",
    synopsis: "A thief who steals corporate secrets through dream-sharing technology is given a chance to erase his past crimes by planting an idea into a target’s subconscious."
  },
  {
    title: "The Hunger Games",
    img: "thehungergames.jpg",
    rating: 3.6,
    duration: "2h 22min",
    year: 2012,
    language: "English", country: "USA", popularity: 2000,
    genre: ["Action", "Adventure"],
    director: "Gary Ross",
    synopsis: "Katniss Everdeen volunteers to take her sister's place in a televised fight to the death in a dystopian future."
  },
  {
    title: "Crazy Rich Asians",
    img: "crazyrichasians.jpg",
    rating: 3.5,
    duration: "2h 1min",
    year: 2018,
    language: "English", country: "USA", popularity: 1800,
    genre: ["Romance", "Comedy"],
    director: "Jon M. Chu",
    synopsis: "An Asian American woman meets her boyfriend’s ultra-rich family in Singapore and discovers his hidden background."
  },
  {
    title: "Letters to Juliet",
    img: "letterstojuliet.jpg",
    rating: 3.2,
    duration: "1h 45min",
    year: 2010,
    language: "English", country: "USA", popularity: 1200,
    genre: ["Romance", "Drama"],
    director: "Gary Winick",
    synopsis: "An aspiring writer in Italy finds a 50-year-old letter to Juliet and sets off to reunite lovers separated by time."
  },
  {
    title: "Maleficent",
    img: "maleficent.jpeg",
    rating: 3.5,
    duration: "1h 37min",
    year: 2014,
    language: "English", country: "USA", popularity: 2200,
    genre: ["Fantasy", "Adventure"],
    director: "Robert Stromberg",
    synopsis: "A vengeful fairy curses an infant princess, but discovers the child may be the only one who can bring peace to their land."
  },
  {
    title: "Joker 2",
    img: "joker_2.jpeg",
    rating: 4.2,
    duration: "2h 18min",
    year: 2024,
    language: "English", country: "USA", popularity: 3000,
    genre: ["Drama", "Crime"],
    director: "Todd Phillips",
    synopsis: "The sequel to Joker continues Arthur Fleck's descent into madness and explores his influence on Gotham’s society."
  },
  {
    title: "Twister",
    img: "twister.webp",
    rating: 3.2,
    duration: "1h 53min",
    year: 1996,
    language: "English", country: "USA", popularity: 1400,
    genre: ["Action", "Thriller"],
    director: "Jan de Bont",
    synopsis: "A team of storm chasers risks their lives to test an experimental weather alert system by chasing deadly tornadoes."
  },
  {
    title: "About Time",
    img: "abouttime.jpg",
    rating: 3.9,
    duration: "2h 3min",
    year: 2013,
    language: "English", country: "UK", popularity: 1600 ,
    genre: ["Romance", "Drama"],
    director: "Richard Curtis",
    synopsis: "A young man discovers he can time travel and uses the ability to improve his love life and make a better future."
  },
  {
    title: "Barbie",
    img: "barbie.jpg",
    rating: 3.6,
    duration: "1h 54min",
    year: 2023,
    language: "English", country: "USA", popularity: 2800,
    genre: ["Comedy", "Fantasy"],
    director: "Greta Gerwig",
    synopsis: "Barbie ventures into the real world to discover the joys and challenges of being human."
  },
  {
    title: "Cruella",
    img: "cruella.jpg",
    rating: 3.7,
    duration: "2h 14min",
    year: 2021,
    language: "English", country: "USA", popularity: 2300,
    genre: ["Comedy", "Crime"],
    director: "Craig Gillespie",
    synopsis: "A rebellious fashion designer in 1970s London transforms into the legendary Cruella de Vil."
  },
  {
    title: "The Lincoln Lawyer",
    img: "thelincolnlawyer.webp",
    rating: 3.6,
    duration: "1h 58min",
    year: 2011,
    language: "English", country: "USA", popularity: 1500,
    genre: ["Drama", "Crime"],
    director: "Brad Furman",
    synopsis: "A defense lawyer operates out of his Lincoln sedan while handling the case of a wealthy client with a dark secret."
  },
  {
    title: "Uglies",
    img: "uglies.jpg",
    rating: 3.4,
    duration: "TBA",
    year: 2025,
    language: "English", country: "USA", popularity: 1100,
    genre: ["Sci-Fi", "Drama"],
    director: "McG",
    synopsis: "In a society where everyone must undergo surgery at 16 to become 'pretty,' one girl questions the system and rebels."
  },
  {
    title: "Hitman",
    img: "hitman.webp",
    rating: 3.1,
    duration: "1h 40min",
    year: 2007,
    language: "English", country: "USA", popularity: 1300,
    genre: ["Action", "Thriller"],
    director: "Xavier Gens",
    synopsis: "A genetically-engineered assassin becomes the target of a political conspiracy and battles forces from both sides."
  },
  {
    title: "Dallas Buyers Club",
    img: "dallasbuyersclub.webp",
    rating: 4.0,
    duration: "1h 57min",
    year: 2013,
    language: "English", country: "USA", popularity: 1700,
    genre: ["Drama"],
    director: "Jean-Marc Vallée",
    synopsis: "Diagnosed with AIDS, a Texas man battles the system and medical establishment to help others access treatment."
  },
  {
    title: "The Amazing Spider-Man",
    img: "amazingspiderman.jpg",
    rating: 3.5,
    duration: "2h 16min",
    year: 2012,
    language: "English", country: "USA", popularity: 2400,
    genre: ["Action", "Adventure"],
    director: "Marc Webb",
    synopsis: "Peter Parker discovers secrets about his past while becoming the superhero Spider-Man."
  },
  {
    title: "Damsel",
    img: "damsel.webp",
    rating: 3.4,
    duration: "1h 50min",
    year: 2023,
    language: "English", country: "USA", popularity: 1000,
    genre: ["Fantasy", "Adventure"],
    director: "Juan Carlos Fresnadillo",
    synopsis: "A young woman agrees to marry a prince, only to discover it’s a trap and she must survive a deadly cave dragon."
  },
  {
    title: "Flipped",
    img: "flipped.jpg",
    rating: 3.9,
    duration: "1h 30min",
    year: 2010,
    language: "English", country: "USA", popularity: 1500,
    genre: ["Romance", "Drama"],
    director: "Rob Reiner",
    synopsis: "Two eighth-graders start to see each other in a different light as they grow up from childhood into adolescence."
  },
  {
    title: "The Age of Adaline",
    img: "theageofadaline.jpg",
    rating: 3.6,
    duration: "1h 52min",
    year: 2015,
    language: "English", country: "USA", popularity: 1400,
    genre: ["Romance", "Drama"],
    director: "Lee Toland Krieger",
    synopsis: "A young woman stops aging after an accident and must hide her secret for decades until she meets someone worth revealing it to."
  },
  {
    title: "The Suicide Squad",
    img: "thesuicidesquad.webp",
    rating: 3.6,
    duration: "2h 12min",
    year: 2021,
    language: "English", country: "USA", popularity: 2600,
    genre: ["Action", "Adventure"],
    director: "James Gunn",
    synopsis: "Supervillains are sent to a remote island on a mission that could reduce their prison sentences — if they survive."
  },
  {
    title: "Begin Again",
    img: "beginagain.jpg",
    rating: 3.7,
    duration: "1h 44min",
    year: 2013,
    language: "English", country: "USA", popularity: 1300,
    genre: ["Romance", "Drama"],
    director: "John Carney",
    synopsis: "A chance encounter between a disgraced music exec and a young singer-songwriter leads to a promising collaboration."
  },
  {
    title: "Mulan",
    img: "mulan.jpg",
    rating: 2.9,
    duration: "1h 55min",
    year: 2020,
    language: "English", country: "USA", popularity: 2000 ,
    genre: ["Action", "Adventure"],
    director: "Niki Caro",
    synopsis: "A young Chinese woman disguises herself as a male warrior to save her father and defend her country."
  },
  {
    title: "Black Panther",
    img: "blackpanther.jpg",
    rating: 3.6,
    duration: "2h 14min",
    year: 2018,
    language: "English", country: "USA", popularity: 3200,
    genre: ["Action", "Sci-Fi"],
    director: "Ryan Coogler",
    synopsis: "T'Challa returns home as king of Wakanda but finds his sovereignty challenged by a new adversary."
  },
  {
    title: "Doctor Strange",
    img: "doctorstrange.jpg",
    rating: 3.8,
    duration: "1h 55min",
    year: 2016,
    language: "English", country: "USA", popularity: 2900,
    genre: ["Action", "Fantasy"],
    director: "Scott Derrickson",
    synopsis: "A brilliant surgeon's career ends with a crash, but mystical forces offer him a new path as a sorcerer."
  },
  {
    title: "Her",
    img: "her.webp",
    rating: 4.0,
    duration: "2h 6min",
    year: 2013,
    language: "English", country: "USA", popularity: 1800,
    genre: ["Drama", "Romance"],
    director: "Spike Jonze",
    synopsis: "In the near future, a lonely writer falls in love with an artificial intelligence system."
  },
  {
    title: "Moana 2",
    img: "moana_2.jpg",
    rating: 3.9,
    duration: "TBA",
    year: 2024,
    language: "English", country: "USA", popularity: 2500,
    genre: ["Animation", "Adventure"],
    director: "Dave Derrick Jr.",
    synopsis: "Moana sets out on a new oceanic journey, encountering fresh challenges beyond the reef."
  },
  {
    title: "Life As We Know It",
    img: "lifeasweknowit.jpg",
    rating: 3.2,
    duration: "1h 54min",
    year: 2010,
    language: "English", country: "USA", popularity: 1200,
    genre: ["Romance", "Comedy"],
    director: "Greg Berlanti",
    synopsis: "Two single adults become caregivers to an orphaned girl when their mutual best friends die in an accident."
  },
  {
    title: "The Dark Knight",
    img: "thedarkknight.jpg",
    rating: 4.5,
    duration: "2h 32min",
    year: 2008,
    language: "English", country: "USA", popularity: 4000,
    genre: ["Action", "Crime"],
    director: "Christopher Nolan",
    synopsis: "Batman faces his greatest psychological and physical tests when the Joker unleashes chaos on Gotham."
  },
  {
    title: "Anyone But You",
    img: "anyonebutyou.webp",
    rating: 3.5,
    duration: "1h 43min",
    year: 2023,
    language: "English", country: "USA", popularity: 1100,
    genre: ["Romance", "Comedy"],
    director: "Will Gluck",
    synopsis: "Two exes pretend to be a couple at a destination wedding, rekindling unresolved feelings."
  },
  {
    title: "Enola Holmes",
    img: "enolaholmes.webp",
    rating: 3.3,
    duration: "2h 3min",
    year: 2020,
    language: "English", country: "USA", popularity: 1500,
    genre: ["Mystery", "Adventure"],
    director: "Harry Bradbeer",
    synopsis: "Sherlock Holmes’ teenage sister embarks on a quest to find her missing mother and outwit villains."
  },
  {
    title: "Walk The Line",
    img: "walktheline.webp",
    rating: 3.9,
    duration: "2h 16min",
    year: 2005,
    language: "English", country: "USA", popularity: 1400,
    genre: ["Biography", "Drama"],
    director: "James Mangold",
    synopsis: "The story of country music legend Johnny Cash and his journey from hardship to fame."
  },
  {
    title: "Meet Yourself",
    img: "meetyourself.webp",
    rating: 3.5,
    duration: "TBA",
    year: 2023,
    language: "English", country: "USA", popularity: 1200,
    genre: ["Drama", "Romance"],
    director: "Ding Zi Guang",
    synopsis: "Burned out from city life, a woman retreats to a rural village and finds healing and new connections."
  },
  {
    title: "Interstellar",
    img: "interstellar.jpg",
    rating: 4.3,
    duration: "2h 49min",
    year: 2014,
    language: "English", country: "USA", popularity: 3500,
    genre: ["Sci-Fi", "Drama"],
    director: "Christopher Nolan",
    synopsis: "A group of explorers travels through a wormhole in space in search of a new home for humanity."
  },
  {
    title: "Five Feet Apart",
    img: "fivefeetapart.jpg",
    rating: 3.6,
    duration: "1h 56min",
    year: 2019,
    language: "English", country: "USA", popularity: 1600,
    genre: ["Romance", "Drama"],
    director: "Justin Baldoni",
    synopsis: "Two teenagers with cystic fibrosis fall in love but must maintain physical distance due to their illness."
  },
  {
    title: "Midnight Sun",
    img: "midnightsun.jpg",
    rating: 3.3,
    duration: "1h 31min",
    year: 2018,
    language: "English", country: "USA", popularity: 1300,
    genre: ["Romance", "Drama"],
    director: "Scott Speer",
    synopsis: "A girl with a rare condition that forces her to avoid sunlight meets a boy and begins to experience love."
  },
  {
    title: "Once Upon A Time",
    img: "onceuponatime.webp",
    rating: 3.8,
    duration: "1h 48min",
    year: 2017,
    language: "English", country: "USA", popularity: 1400,
    genre: ["Fantasy", "Romance"],
    director: "Zhao Xiaoding, Anthony LaMolinara",
    synopsis: "A love story unfolds over lifetimes and worlds, testing the limits of fate and devotion."
  }
];