const hardcodedMovies = [
    { title: "La La Land", img: "lalaland.jpg", genre: ["Romance", "Drama"], year: 2016, rating: 8.0, language: "English", country: "USA", popularity: 2500 },
    { title: "Inception", img: "inception.jpg", genre: ["Action", "Sci-Fi"], year: 2010, rating: 8.8, language: "English", country: "USA", popularity: 3500 },
    { title: "Crazy Rich Asians", img: "crazyrichasians.jpg", genre: ["Romance", "Comedy"], year: 2018, rating: 7.0, language: "English", country: "USA", popularity: 1800 },
    { title: "Letters to Juliet", img: "letterstojuliet.webp", genre: ["Romance", "Drama"], year: 2010, rating: 6.5, language: "English", country: "USA", popularity: 1200 },
    { title: "Maleficent", img: "maleficent.webp", genre: ["Fantasy", "Adventure"], year: 2014, rating: 7.0, language: "English", country: "USA", popularity: 2200 },
    { title: "Twister", img: "twister.webp", genre: ["Action", "Thriller"], year: 1996, rating: 6.4, language: "English", country: "USA", popularity: 1400 },
    { title: "About Time", img: "abouttime.jpg", genre: ["Romance", "Drama"], year: 2013, rating: 7.8, language: "English", country: "UK", popularity: 1600 },
    { title: "Barbie", img: "barbie.webp", genre: ["Comedy", "Fantasy"], year: 2023, rating: 7.3, language: "English", country: "USA", popularity: 2800 },
    { title: "Cruella", img: "cruella.jpg", genre: ["Comedy", "Crime"], year: 2021, rating: 7.4, language: "English", country: "USA", popularity: 2300 },
    { title: "The Lincoln Lawyer", img: "thelincolnlawyer.webp", genre: ["Drama", "Crime"], year: 2011, rating: 7.3, language: "English", country: "USA", popularity: 1500 },
    { title: "Uglies", img: "uglies.webp", genre: ["Sci-Fi", "Drama"], year: 2024, rating: 6.8, language: "English", country: "USA", popularity: 1100 },
    { title: "Dallas Buyers Club", img: "dallasbuyersclub.webp", genre: ["Drama"], year: 2013, rating: 8.0, language: "English", country: "USA", popularity: 1700 },
    { title: "The Amazing Spider-Man", img: "theamazingspiderman.webp", genre: ["Action", "Adventure"], year: 2012, rating: 6.9, language: "English", country: "USA", popularity: 2400 },
    { title: "Damsel", img: "damsel.webp", genre: ["Fantasy", "Adventure"], year: 2024, rating: 6.7, language: "English", country: "USA", popularity: 1000 },
    { title: "Flipped", img: "flipped.webp", genre: ["Romance", "Drama"], year: 2010, rating: 7.7, language: "English", country: "USA", popularity: 1500 },
    { title: "The Suicide Squad", img: "thesuicidesquad.webp", genre: ["Action", "Comedy"], year: 2021, rating: 7.2, language: "English", country: "USA", popularity: 2600 },
    { title: "Begin Again", img: "beginagain.jpg", genre: ["Romance", "Music"], year: 2014, rating: 7.4, language: "English", country: "USA", popularity: 1300 },
    { title: "Mulan", img: "mulan.webp", genre: ["Action", "Adventure"], year: 2020, rating: 5.7, language: "English", country: "USA", popularity: 2000 },
    { title: "Black Panther", img: "blackpanther.jpg", genre: ["Action", "Adventure"], year: 2018, rating: 7.3, language: "English", country: "USA", popularity: 3200 },
    { title: "Doctor Strange", img: "doctorstrange.webp", genre: ["Action", "Fantasy"], year: 2016, rating: 7.5, language: "English", country: "USA", popularity: 2900 },
    { title: "Her", img: "her.webp", genre: ["Romance", "Sci-Fi"], year: 2013, rating: 8.0, language: "English", country: "USA", popularity: 1800 },
    { title: "Moana 2", img: "moana_2.jpg", genre: ["Animation", "Adventure"], year: 2024, rating: 7.8, language: "English", country: "USA", popularity: 2500 },
    { title: "Life As We Know It", img: "lifeasweknowit.webp", genre: ["Romance", "Comedy"], year: 2010, rating: 6.5, language: "English", country: "USA", popularity: 1200 },
    { title: "The Dark Knight", img: "thedarkknight.jpg", genre: ["Action", "Crime"], year: 2008, rating: 9.0, language: "English", country: "USA", popularity: 4000 },
    { title: "Anyone But You", img: "anyonebutyou.webp", genre: ["Romance", "Comedy"], year: 2023, rating: 6.9, language: "English", country: "USA", popularity: 1100 },
    { title: "Enola Holmes", img: "enolaholmes.webp", genre: ["Mystery", "Adventure"], year: 2020, rating: 6.6, language: "English", country: "USA", popularity: 1500 },
    { title: "Walk The Line", img: "walktheline.webp", genre: ["Drama", "Music"], year: 2005, rating: 7.8, language: "English", country: "USA", popularity: 1400 },
    { title: "Interstellar", img: "interstellar.webp", genre: ["Sci-Fi", "Adventure"], year: 2014, rating: 8.6, language: "English", country: "USA", popularity: 3500 },
    { title: "Five Feet Apart", img: "fivefeetapart.jpg", genre: ["Romance", "Drama"], year: 2019, rating: 7.2, language: "English", country: "USA", popularity: 1600 },
    { title: "Midnight Sun", img: "midnightsun.webp", genre: ["Romance", "Drama"], year: 2018, rating: 6.6, language: "English", country: "USA", popularity: 1300 }
    ];